// Generated by scripts/generate_models.py. Do not edit manually.

export interface AutoUpdateConfigRequest {
  enabled: boolean;
  hour?: number | null;
}

export interface AutoUpdateRun {
  triggered_at: string;
  completed_at: string;
  status: string;
  trigger?: string;
  operation?: string;
  filter_count?: number;
  detail?: string | null;
  downloaded?: Array<string>;
  redownloaded?: Array<string>;
  verified_existing?: Array<string>;
}

export interface AutoUpdateStatusResponse {
  test_mode?: boolean;
  enabled: boolean;
  hour?: number | null;
  timezone: string;
  current_time: string;
  next_update_at?: string | null;
  active?: boolean;
  active_since?: string | null;
  live_logs?: Array<string>;
  history?: Array<AutoUpdateRun>;
}

export interface BatchCheckRequest {
  credentials: Array<CheckRequest>;
}

export interface BatchCheckResponse {
  test_mode?: boolean;
  total: number;
  found_usernames: Array<string>;
}

export interface BatchHashCheckRequest {
  hashes: Array<string>;
}

export interface BatchHashCheckResponse {
  test_mode?: boolean;
  total: number;
  found_hashes: Array<string>;
}

export interface CheckRequest {
  username: string;
  password?: string;
}

export interface CheckResponse {
  test_mode?: boolean;
  found: boolean;
  matching_filters: Array<string>;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface HealthResponse {
  status: string;
  filters_loaded: number;
  test_mode: boolean;
}

export interface ManifestUpdateResponse {
  test_mode?: boolean;
  success: boolean;
  output_file?: string | null;
  filter_count?: number;
  logs?: Array<string>;
  detail?: string | null;
}

export interface ReloadFiltersResponse {
  test_mode?: boolean;
  success: boolean;
  filter_count?: number;
  filters?: Array<string>;
  max_nk?: number;
  logs?: Array<string>;
  detail?: string | null;
}

export interface RootResponse {
  name: string;
  version: string;
  endpoints: Record<string, unknown>;
  test_mode: boolean;
}

export interface SingleHashCheckRequest {
  hash: string;
}

export interface StatsResponse {
  test_mode?: boolean;
  filter_count: number;
  filters: Array<string>;
  max_nk: number;
}

export interface SyncApplyStartResponse {
  test_mode?: boolean;
  started: boolean;
  operation: string;
  detail?: string | null;
}

export interface SyncFiltersResponse {
  test_mode?: boolean;
  success: boolean;
  manifest_path?: string | null;
  downloaded?: Array<string>;
  redownloaded?: Array<string>;
  verified_existing?: Array<string>;
  logs?: Array<string>;
  detail?: string | null;
}

export interface SyncStatusResponse {
  test_mode?: boolean;
  active: boolean;
  operation?: string | null;
  logs?: Array<string>;
  success?: boolean | null;
  detail?: string | null;
  manifest_path?: string | null;
  output_file?: string | null;
  downloaded?: Array<string>;
  redownloaded?: Array<string>;
  verified_existing?: Array<string>;
  filter_count?: number;
  filters?: Array<string>;
  max_nk?: number;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}
