"""Generated by scripts/generate_models.py. Do not edit manually."""
from __future__ import annotations

from typing import Any, NotRequired, TypedDict


class AutoUpdateConfigRequest(TypedDict):
    enabled: bool
    hour: NotRequired[int | None]

class AutoUpdateRun(TypedDict):
    triggered_at: str
    completed_at: str
    status: str
    trigger: NotRequired[str]
    operation: NotRequired[str]
    filter_count: NotRequired[int]
    detail: NotRequired[str | None]
    downloaded: NotRequired[list[str]]
    redownloaded: NotRequired[list[str]]
    verified_existing: NotRequired[list[str]]

class AutoUpdateStatusResponse(TypedDict):
    test_mode: NotRequired[bool]
    enabled: bool
    hour: NotRequired[int | None]
    timezone: str
    current_time: str
    next_update_at: NotRequired[str | None]
    active: NotRequired[bool]
    active_since: NotRequired[str | None]
    live_logs: NotRequired[list[str]]
    history: NotRequired[list[AutoUpdateRun]]

class BatchCheckRequest(TypedDict):
    credentials: list[CheckRequest]

class BatchCheckResponse(TypedDict):
    test_mode: NotRequired[bool]
    total: int
    found_usernames: list[str]

class BatchHashCheckRequest(TypedDict):
    hashes: list[str]

class BatchHashCheckResponse(TypedDict):
    test_mode: NotRequired[bool]
    total: int
    found_hashes: list[str]

class CheckRequest(TypedDict):
    username: str
    password: NotRequired[str]

class CheckResponse(TypedDict):
    test_mode: NotRequired[bool]
    found: bool
    matching_filters: list[str]

class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]

class HealthResponse(TypedDict):
    status: str
    filters_loaded: int
    test_mode: bool

class ManifestUpdateResponse(TypedDict):
    test_mode: NotRequired[bool]
    success: bool
    output_file: NotRequired[str | None]
    filter_count: NotRequired[int]
    logs: NotRequired[list[str]]
    detail: NotRequired[str | None]

class ReloadFiltersResponse(TypedDict):
    test_mode: NotRequired[bool]
    success: bool
    filter_count: NotRequired[int]
    filters: NotRequired[list[str]]
    max_nk: NotRequired[int]
    logs: NotRequired[list[str]]
    detail: NotRequired[str | None]

class RootResponse(TypedDict):
    name: str
    version: str
    endpoints: dict[str, Any]
    test_mode: bool

class SingleHashCheckRequest(TypedDict):
    hash: str

class StatsResponse(TypedDict):
    test_mode: NotRequired[bool]
    filter_count: int
    filters: list[str]
    max_nk: int

class SyncApplyStartResponse(TypedDict):
    test_mode: NotRequired[bool]
    started: bool
    operation: str
    detail: NotRequired[str | None]

class SyncFiltersResponse(TypedDict):
    test_mode: NotRequired[bool]
    success: bool
    manifest_path: NotRequired[str | None]
    downloaded: NotRequired[list[str]]
    redownloaded: NotRequired[list[str]]
    verified_existing: NotRequired[list[str]]
    logs: NotRequired[list[str]]
    detail: NotRequired[str | None]

class SyncStatusResponse(TypedDict):
    test_mode: NotRequired[bool]
    active: bool
    operation: NotRequired[str | None]
    logs: NotRequired[list[str]]
    success: NotRequired[bool | None]
    detail: NotRequired[str | None]
    manifest_path: NotRequired[str | None]
    output_file: NotRequired[str | None]
    downloaded: NotRequired[list[str]]
    redownloaded: NotRequired[list[str]]
    verified_existing: NotRequired[list[str]]
    filter_count: NotRequired[int]
    filters: NotRequired[list[str]]
    max_nk: NotRequired[int]

class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]
