"""Generate static SDK types from the checked-in API contract; no dependencies."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def type_name(schema: dict, language: str) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "anyOf" in schema:
        return " | ".join(type_name(s, language) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        item = type_name(schema.get("items", {}), language)
        return f"list[{item}]" if language == "py" else f"Array<{item}>"
    names = {
        "string": ("str", "string"), "integer": ("int", "number"),
        "number": ("float", "number"), "boolean": ("bool", "boolean"),
        "null": ("None", "null"), "object": ("dict[str, Any]", "Record<string, unknown>"),
        None: ("Any", "unknown"),
    }
    return names[kind][0 if language == "py" else 1]


def generate() -> dict[Path, str]:
    schemas = json.loads((ROOT / "api/openapi.json").read_text(encoding="utf-8"))["components"]["schemas"]
    # These two routes return unannotated dictionaries in api.py and have empty
    # OpenAPI schemas. Keep their source-verified types alongside generated types.
    schemas.update({
        "RootResponse": {"required": ["name", "version", "endpoints", "test_mode"], "properties": {
            "name": {"type": "string"}, "version": {"type": "string"},
            "endpoints": {"type": "object"}, "test_mode": {"type": "boolean"}}},
        "HealthResponse": {"required": ["status", "filters_loaded", "test_mode"], "properties": {
            "status": {"type": "string"}, "filters_loaded": {"type": "integer"},
            "test_mode": {"type": "boolean"}}},
    })
    py = ['"""Generated by scripts/generate_models.py. Do not edit manually."""',
          "from __future__ import annotations", "", "from typing import Any, NotRequired, TypedDict", ""]
    ts = ["// Generated by scripts/generate_models.py. Do not edit manually.", ""]
    for name, schema in sorted(schemas.items()):
        py.extend(["", f"class {name}(TypedDict):"])
        ts.append(f"export interface {name} {{")
        required = schema.get("required", [])
        for field, definition in schema.get("properties", {}).items():
            ptype = type_name(definition, "py")
            optional = field not in required
            py.append(f"    {field}: {f'NotRequired[{ptype}]' if optional else ptype}")
            ts.append(f"  {field}{'?' if optional else ''}: {type_name(definition, 'ts')};")
        ts.extend(["}", ""])
    return {
        ROOT / "python/src/hushclient/models.py": "\n".join(py) + "\n",
        ROOT / "typescript/src/models.ts": "\n".join(ts),
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale generated file: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")

